## Default configuration
conf:
  layoutName: "default-settings" # Machine-name of layout
  description: "Default settings" # Description

  # Rendering options
  defaultType: "div" # If type is not defined then this will be used. If null is set, nothing will be rendered.
  idAuto: true # Automatically generates the id attribute.
  classAuto: true # Automatically generates the class attribute.

  # Wrapper container settings
  wrapper: false # Inserts a container that contains the element to be rendered.
  wrapperClass: "wrapper" # The class that will be added to each wrapper element if "classAuto: true"
  wrapperPrefix: "" # The class and id prefix if "classAuto: true" or "idAuto: true"
  wrapperSuffix: "-wrapper" # The suffix of classes and ids if "classAuto: true" or "idAuto: true"

  # Element container settings
  element: true # Container of the item to render
  elementClass: "" # The class that will be added to each element if "classAuto: true"
  elementPrefix: "" # The class and id prefix if "classAuto: true" or "idAuto: true"
  elementSuffix: "" # The suffix of classes and ids if "classAuto: true" or "idAuto: true"

  # Inner container settings
  inner: false # Inserts a container inside the element to be generated
  innerClass: "inner" # The class that will be added to each inner element if "classAuto: true"
  innerPrefix: "" # The class and id prefix if "classAuto: true" or "idAuto: true"
  innerSuffix: "-inner" # The suffix of classes and ids if "classAuto: true" or "idAuto: true"

  # Region container settings
  region: true # Container of the single region, it is advisable to always leave on true except very special cases
  renderRegionFirst: true # If items and regions are defined on the same level, the region region will be rendered before the items if this value is "true"
  regionClass: "region" # The class that will be added to each region element if "classAuto: true"
  regionPrefix: "" # The class and id prefix if "classAuto: true" or "idAuto: true"
  regionSuffix: "" # The suffix of classes and ids if "classAuto: true" or "idAuto: true"

  debugBlock: false # Content block rendered after the region, it is useful in development as it,displays the page structure with no content generated by the CMS
  debugBlockOnly: false # Show only the debug block
  debugBlockClass: "debugBlock well" # La classe che verr√† impostata ad ogni regione
  debugBlockPrefix: "" # The class that will be added to each debugBlock element if "classAuto: true"
  debugBlockSuffix: "-debugBlock" # The suffix of classes and ids if "classAuto: true" or "idAuto: true"

  compressOutput: false # For compress output set "true". For indent output set "false".
  compressOutputAutoDeactivate: true # Turn true compressOutput if injectTag is setting, there are issue with tidy.
  compressOption: # See tidy configuration http://api.html-tidy.org/
    indent: true
    show-body-only: true

layingCore:
  containerList: [ "wrapper", "element", "inner", "region" ]  # Lista dei container
  containerDefault: "element" # Il container scelto deve essere impostato su true, settare su false per non scegliere nessuno